# This file is automatically generated by Android Studio.
# It contains the safe configure flags for the given library
# Usage is typically to add it to your app's proguard-rules.pro configuration.

-keepclasseswithmembernames class * {
    native <methods>;
}

-keep class * {
    public protected <init>(...);
}
